{
 "title": "Thailand",
 "description": "This is a dashboard to display Thailand air quality.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 27/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1729962000 AS 'time_to',\r\n'Past 24 Hours' as 'button_text'"
    },
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 29/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1730134800 AS 'time_to',\r\n'Past 3 Days' as 'button_text'"
    },
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 31/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1730307600 AS 'time_to',\r\n'Past 5 Days' as 'button_text'"
    }
   ]
  },
  {
   "title": "Average AQI for PM2.5 by Station",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.latitude AS lat,L.longitude AS lng,AVG(T.AQI) AS avg_AQI\r\nFROM Thailand T\r\nJOIN \r\n    Location L ON T.location_id = L.location_id\r\nWHERE L.region = 'Thailand'\r\n    AND $__timeFilter(T.recorded_at)\r\nGROUP BY L.location_id, L.latitude, L.longitude;\r\n"
    }
   ]
  },
  {
   "title": "Bangkok Metropolitan Area in Thailand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 225629"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<p><b>Average Pollutants by Station:</b><br>\r\n  1) Bangkok(MA): Nonthaburi,\r\n  2) North: Chiangrai,\r\n  3) Northeast: Sakon Nakhon,\r\n  4) East: Chanthaburi,\r\n  5) South: Trang,\r\n  6) West: Prachuap Khiri Khan\r\n</P>\r\n\r\n\r\n\r\n\r\n\r\n"
   }
  },
  {
   "title": "Average AQI for PM2.5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI, recorded_at \r\nFROM air_quality.Thailand\r\nWHERE $__timeFilter(recorded_at)\r\n"
    }
   ]
  },
  {
   "title": "Eastern Thailand",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 353740"
    }
   ]
  },
  {
   "title": "Most Polluted Station",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.location_city, T.avg_AQI\r\nFROM (\r\n    SELECT location_id, AVG(AQI) AS avg_AQI\r\n    FROM Thailand\r\n    WHERE $__timeFilter(recorded_at)\r\n    GROUP BY location_id\r\n) AS T\r\nJOIN \r\n    Location AS L ON T.location_id = L.location_id\r\nORDER BY T.avg_AQI DESC\r\nLIMIT 1;\r\n"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT recorded_at FROM air_quality.Thailand LIMIT 50 "
    }
   ]
  },
  {
   "title": "Least Polluted Station",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.location_city, T.avg_AQI\r\nFROM (\r\n    SELECT location_id, AVG(AQI) AS avg_AQI\r\n    FROM Thailand\r\n    WHERE $__timeFilter(recorded_at)\r\n    GROUP BY location_id\r\n) AS T\r\nJOIN\r\n    Location AS L ON T.location_id = L.location_id\r\nORDER BY T.avg_AQI ASC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Northern Thailand",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 225567"
    }
   ]
  },
  {
   "title": "Southern Thailand",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 228627"
    }
   ]
  },
  {
   "title": "Average Pollutants (µg/m³)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co \r\nFROM air_quality.Thailand \r\nWHERE $__timeFilter(recorded_at)"
    }
   ]
  },
  {
   "title": "Northeastern Thailand",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 228544"
    }
   ]
  },
  {
   "title": "Western Thailand",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, pm10, no2, o3, so2, co, recorded_at \r\nFROM air_quality.Thailand \r\nWHERE location_id = 354124"
    }
   ]
  }
 ]
}