{
 "title": "Worldwide",
 "description": "This is a dashboard to display air quality in cities worldwide.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 27/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1729962000 AS 'time_to',\r\n'Past 24 Hours' as 'button_text'"
    },
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 29/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1730134800 AS 'time_to',\r\n'Past 3 Days' as 'button_text'"
    },
    {
     "dataset": "air_quality",
     "rawSql": "-- 26/10/2024 00:00:00(GMT+0700) to 31/10/2024 00:00:00(GMT+0700)\r\nSELECT \t1729875600 AS 'time_form',\r\n1730307600 AS 'time_to',\r\n'Past 5 Days' as 'button_text'"
    }
   ]
  },
  {
   "title": "Average AQI for PM2.5 by Station",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 11, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.latitude AS lat,L.longitude AS lng,AVG(W.AQI) AS avg_AQI\r\nFROM Worldwide W\r\nJOIN \r\n    Location L ON W.location_id = L.location_id\r\nWHERE L.region = 'Worldwide'\r\n    AND $__timeFilter(W.recorded_at)\r\nGROUP BY L.location_id, L.latitude, L.longitude;\r\n"
    }
   ]
  },
  {
   "title": "Average AQI for PM2.5 by Station",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 1324 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 589967 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 2162178 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 1590755 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 8118 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 225617 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 1214722 LIMIT 50 "
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI FROM air_quality.Worldwide WHERE location_id = 9466 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average AQI for PM2.5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT AQI, recorded_at \r\nFROM air_quality.Worldwide\r\nWHERE $__timeFilter(recorded_at)\r\n"
    }
   ]
  },
  {
   "title": "Most Polluted Station",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.location_city, T.avg_AQI\r\nFROM (\r\n    SELECT location_id, AVG(AQI) AS avg_AQI\r\n    FROM Worldwide\r\n    WHERE $__timeFilter(recorded_at)\r\n    GROUP BY location_id\r\n) AS T\r\nJOIN \r\n    Location AS L ON T.location_id = L.location_id\r\nORDER BY T.avg_AQI DESC\r\nLIMIT 1;\r\n"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT recorded_at FROM air_quality.Thailand LIMIT 50 "
    }
   ]
  },
  {
   "title": "Least Polluted Station",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT L.location_city, T.avg_AQI\r\nFROM (\r\n    SELECT location_id, AVG(AQI) AS avg_AQI\r\n    FROM Worldwide\r\n    WHERE $__timeFilter(recorded_at)\r\n    GROUP BY location_id\r\n) AS T\r\nJOIN\r\n    Location AS L ON T.location_id = L.location_id\r\nORDER BY T.avg_AQI ASC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Historic PM2.5 by Station",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 6, "y": 11 },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at \r\nFROM air_quality.Worldwide \r\nWHERE location_id = 1324"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 589967\r\n"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 2162178\r\n"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 1590755"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 8118"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 225617"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 1214722"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25, recorded_at\r\nFROM air_quality.Worldwide\r\nWHERE location_id = 9466"
    }
   ]
  },
  {
   "title": "Average PM2.5 by Station (μg/m³)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 1324"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 589967"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 2162178"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 1590755"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 8118"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 225617"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 1214722"
    },
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25 FROM air_quality.Worldwide WHERE location_id = 9466"
    }
   ]
  },
  {
   "title": "Average Pollutants (µg/m³)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "air_quality",
     "rawSql": "SELECT pm25\r\nFROM air_quality.Worldwide\r\nWHERE $__timeFilter(recorded_at)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "options": {
    "content": "<p><b>Station:</b><br>\r\n  1) North America(US): Florida,\r\n  2) South America(Brazil): Sao Paulo,\r\n  3) Europe(Germany): Berlin,\r\n  4) Africa(South Africa): Cape Town,\r\n  5) Asia(India): New Delhi,\r\n  6) Asia(Thailand): Bangkok,\r\n  7) Asia(Japan): Tokyo,\r\n  8) Australia: Canberra\r\n</P>\r\n\r\n\r\n\r\n\r\n\r\n"
   }
  }
 ]
}